/*

 BIRD.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

const int bird_size = 32;


/* Start of tile array. */
unsigned char bird[] =
{
  0x00,0x00,0x1C,0x1C,0xAA,0xB2,0xCD,0xF3,
  0xE2,0xFE,0x9C,0x9C,0x00,0x00,0x00,0x00
};

/* End of BIRD.C */
