/*

 DOWNPIPE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char DownPipe[] =
{
  0x52,0x4E,0x52,0x4E,0x52,0x4E,0x52,0x4E,
  0x52,0x4E,0x52,0x4E,0x52,0x4E,0x52,0x4E,
  0x52,0x4E,0x52,0x4E,0x52,0x4E,0x52,0x4E,
  0xFF,0xFF,0xB1,0x8F,0xB1,0x8F,0xFF,0xFF
};

/* End of DOWNPIPE.C */
